name: Release RISC-V VM
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Next Version (e.g. v1.0.0). Check Releases for last version.'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build-binaries:
    name: Build Binary ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: riscv-vm
            asset_name: riscv-vm-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: riscv-vm
            asset_name: riscv-vm-darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: riscv-vm
            asset_name: riscv-vm-darwin-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build -p riscv-vm --release --target ${{ matrix.target }}

      - name: Rename binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          mv ${{ matrix.binary_name }} ../../../${{ matrix.asset_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}

  create-release:
    needs: [build-binaries]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: riscv-vm-*
          merge-multiple: true

      - name: List artifacts
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: riscv-vm-${{ inputs.version }}
          name: RISC-V VM ${{ inputs.version }}
          files: artifacts/*
          generate_release_notes: true

